defaults:
  - default
  - _self_

batch_opt:
  batch_delay: 1
  train_L_batch: false
  train_L_time: false
  train_L_space: false

model:
  name: agcrn
  hparams:
    hidden_size: 64
    n_layers: 2
    emb_size: 10

optimizer:
  hparams:
    lr: 0.003

lr_scheduler: null


wandb:
  offline: false
  project: "tsl_traffic"