defaults:
  - default
  - _self_
  
batch_size: 64

batch_opt:
  batch_delay: 1
  train_L_batch: false
  train_L_time: false
  train_L_space: false

model:
  name: dcrnn
  hparams:
    hidden_size: 64
    ff_size: 128
    kernel_size: 2
    n_layers: 1
    dropout: 0

dataset:
  connectivity:
    layout: csr

optimizer:
  hparams:
    lr: 0.01

lr_scheduler:
  name: MultiStepLR
  hparams:
    gamma: 0.1
    milestones: [ 20, 30, 40 ]

wandb:
  offline: false
  project: "tsl_traffic"