defaults:
  - default
  - _self_

batch_size: 64
l2_reg: 0.0001
lr: 0.001

batch_opt:
  batch_delay: 1
  train_L_batch: false
  train_L_time: false
  train_L_space: false

model:
  name: stcn
  hparams:
    hidden_size: 32
    ff_size: 256
    n_layers: 4
    dropout: 0.1
    temporal_kernel_size: 2
    spatial_kernel_size: 2
    dilation: 2
    norm: batch

dataset:
  connectivity:
    layout: csr

optimizer:
  hparams:
    lr: 0.01

lr_scheduler: null

wandb:
  offline: false
  project: "tsl_traffic"